apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pbhcga7iu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pbhcga7iu-python 
  name: pbhcga7iu-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pbhcga7iu-python 
